name: Build Server

on:
  push:
    paths:
      - '**.ps1'
      - '**.yml'
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        branch: ['master', "3.6.0"]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: Run build script
        id: build
        shell: pwsh
        run: ./build_server.ps1 -Overwrite -Branch ${{matrix.branch}}

      - run: echo "$FILE_NAME"
        env:
          FILE_NAME: ${{ steps.build.outputs.ZIP_NAME }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.build.outputs.ZIP_NAME }}
          path: './Server/${{ steps.build.outputs.ZIP_NAME }}'
          if-no-files-found: error
          retention-days: 3

      
